
version: 0.2
phases:
  install:
    commands:
      - pip install aws-sam-cli
      - npm install
  pre_build:
    commands:
      - npm run test
      - npm prune --production
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml

