version: 0.2
phases:
  pre_build:
    commands:
      - pip3 install pytest
      - python3 -m pytest tests/unit/ -v
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml
